# version: 0.0
# os: linux
# files:
#   - source: /
#     destination: /home/ec2-user/nodejs-aws-codedeploy-pipeline
# hooks:
# # ApplicationStop:
# # DownloadBundle:
# #  BeforeInstall:
# #    - location: scripts/before_install.sh
# #      timeout: 300
# #      runas: root
# # Install:
#   AfterInstall:
#     - location: scripts/after_install.sh
#       timeout: 300
#       runas: root
#   ApplicationStart:
#     - location: scripts/application_start.sh
#       timeout: 300
#       runas: root
# # ValidateService:

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nodejs-aws-codedeploy-pipeline

hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  Install:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ec2-user
